/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'admin-home': RouteRecordInfo<'admin-home', '/admin/home', Record<never, never>, Record<never, never>>,
    'admin-pipeline-closed-tab': RouteRecordInfo<'admin-pipeline-closed-tab', '/admin/pipeline/closed/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'admin-pipeline-contacts-tab': RouteRecordInfo<'admin-pipeline-contacts-tab', '/admin/pipeline/contacts/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'admin-pipeline-leads-tab': RouteRecordInfo<'admin-pipeline-leads-tab', '/admin/pipeline/leads/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'admin-pipeline-new': RouteRecordInfo<'admin-pipeline-new', '/admin/pipeline/new', Record<never, never>, Record<never, never>>,
    'admin-pipeline-opportunity-tab': RouteRecordInfo<'admin-pipeline-opportunity-tab', '/admin/pipeline/opportunity/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'anchor': RouteRecordInfo<'anchor', '/anchor', Record<never, never>, Record<never, never>>,
    'anchors': RouteRecordInfo<'anchors', '/anchors', Record<never, never>, Record<never, never>>,
    'apps-academy-course-details': RouteRecordInfo<'apps-academy-course-details', '/apps/academy/course-details', Record<never, never>, Record<never, never>>,
    'apps-academy-dashboard': RouteRecordInfo<'apps-academy-dashboard', '/apps/academy/dashboard', Record<never, never>, Record<never, never>>,
    'apps-academy-my-course': RouteRecordInfo<'apps-academy-my-course', '/apps/academy/my-course', Record<never, never>, Record<never, never>>,
    'apps-calendar': RouteRecordInfo<'apps-calendar', '/apps/calendar', Record<never, never>, Record<never, never>>,
    'apps-chat': RouteRecordInfo<'apps-chat', '/apps/chat', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-customer-details-id': RouteRecordInfo<'apps-ecommerce-customer-details-id', '/apps/ecommerce/customer/details/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-ecommerce-customer-list': RouteRecordInfo<'apps-ecommerce-customer-list', '/apps/ecommerce/customer/list', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-manage-review': RouteRecordInfo<'apps-ecommerce-manage-review', '/apps/ecommerce/manage-review', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-order-details-id': RouteRecordInfo<'apps-ecommerce-order-details-id', '/apps/ecommerce/order/details/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-ecommerce-order-list': RouteRecordInfo<'apps-ecommerce-order-list', '/apps/ecommerce/order/list', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-product-add': RouteRecordInfo<'apps-ecommerce-product-add', '/apps/ecommerce/product/add', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-product-category-list': RouteRecordInfo<'apps-ecommerce-product-category-list', '/apps/ecommerce/product/category-list', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-product-list': RouteRecordInfo<'apps-ecommerce-product-list', '/apps/ecommerce/product/list', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-referrals': RouteRecordInfo<'apps-ecommerce-referrals', '/apps/ecommerce/referrals', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-settings': RouteRecordInfo<'apps-ecommerce-settings', '/apps/ecommerce/settings', Record<never, never>, Record<never, never>>,
    'apps-email': RouteRecordInfo<'apps-email', '/apps/email', Record<never, never>, Record<never, never>>,
    'apps-invoice-add': RouteRecordInfo<'apps-invoice-add', '/apps/invoice/add', Record<never, never>, Record<never, never>>,
    'apps-invoice-edit-id': RouteRecordInfo<'apps-invoice-edit-id', '/apps/invoice/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-invoice-list': RouteRecordInfo<'apps-invoice-list', '/apps/invoice/list', Record<never, never>, Record<never, never>>,
    'apps-invoice-preview-id': RouteRecordInfo<'apps-invoice-preview-id', '/apps/invoice/preview/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-logistics-dashboard': RouteRecordInfo<'apps-logistics-dashboard', '/apps/logistics/dashboard', Record<never, never>, Record<never, never>>,
    'apps-logistics-fleet': RouteRecordInfo<'apps-logistics-fleet', '/apps/logistics/fleet', Record<never, never>, Record<never, never>>,
    'apps-permissions': RouteRecordInfo<'apps-permissions', '/apps/permissions', Record<never, never>, Record<never, never>>,
    'apps-roles': RouteRecordInfo<'apps-roles', '/apps/roles', Record<never, never>, Record<never, never>>,
    'apps-user-list': RouteRecordInfo<'apps-user-list', '/apps/user/list', Record<never, never>, Record<never, never>>,
    'apps-user-test': RouteRecordInfo<'apps-user-test', '/apps/user/test', Record<never, never>, Record<never, never>>,
    'apps-user-view-id': RouteRecordInfo<'apps-user-view-id', '/apps/user/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-email-filter': RouteRecordInfo<'apps-email-filter', '/apps/email/:filter', { filter: ParamValue<true> }, { filter: ParamValue<false> }>,
    'apps-email-label': RouteRecordInfo<'apps-email-label', '/apps/email/:label', { label: ParamValue<true> }, { label: ParamValue<false> }>,
    'bank-banks': RouteRecordInfo<'bank-banks', '/bank/banks', Record<never, never>, Record<never, never>>,
    'bank-forms-configuration': RouteRecordInfo<'bank-forms-configuration', '/bank/forms/configuration', Record<never, never>, Record<never, never>>,
    'bank-forms-terms-conditions': RouteRecordInfo<'bank-forms-terms-conditions', '/bank/forms/terms-conditions', Record<never, never>, Record<never, never>>,
    'bank-forms-user-manual': RouteRecordInfo<'bank-forms-user-manual', '/bank/forms/user-manual', Record<never, never>, Record<never, never>>,
    'bank-masterlist': RouteRecordInfo<'bank-masterlist', '/bank/masterlist', Record<never, never>, Record<never, never>>,
    'bank-new': RouteRecordInfo<'bank-new', '/bank/new', Record<never, never>, Record<never, never>>,
    'bank-new-bank-logo': RouteRecordInfo<'bank-new-bank-logo', '/bank/new/BankLogo', Record<never, never>, Record<never, never>>,
    'bank-new-user-manuals': RouteRecordInfo<'bank-new-user-manuals', '/bank/new/UserManuals', Record<never, never>, Record<never, never>>,
    'bank-view-id': RouteRecordInfo<'bank-view-id', '/bank/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'buyers': RouteRecordInfo<'buyers', '/buyers', Record<never, never>, Record<never, never>>,
    'calendar-follow-up-modal': RouteRecordInfo<'calendar-follow-up-modal', '/calendar/FollowUpModal', Record<never, never>, Record<never, never>>,
    'calendar-followups': RouteRecordInfo<'calendar-followups', '/calendar/followups', Record<never, never>, Record<never, never>>,
    'calendar-schedules': RouteRecordInfo<'calendar-schedules', '/calendar/schedules', Record<never, never>, Record<never, never>>,
    'charts-apex-chart': RouteRecordInfo<'charts-apex-chart', '/charts/apex-chart', Record<never, never>, Record<never, never>>,
    'charts-chartjs': RouteRecordInfo<'charts-chartjs', '/charts/chartjs', Record<never, never>, Record<never, never>>,
    'companies-edit-id': RouteRecordInfo<'companies-edit-id', '/companies/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'companies-view-id': RouteRecordInfo<'companies-view-id', '/companies/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'company': RouteRecordInfo<'company', '/company', Record<never, never>, Record<never, never>>,
    'components-alert': RouteRecordInfo<'components-alert', '/components/alert', Record<never, never>, Record<never, never>>,
    'components-avatar': RouteRecordInfo<'components-avatar', '/components/avatar', Record<never, never>, Record<never, never>>,
    'components-badge': RouteRecordInfo<'components-badge', '/components/badge', Record<never, never>, Record<never, never>>,
    'components-button': RouteRecordInfo<'components-button', '/components/button', Record<never, never>, Record<never, never>>,
    'components-chip': RouteRecordInfo<'components-chip', '/components/chip', Record<never, never>, Record<never, never>>,
    'components-dialog': RouteRecordInfo<'components-dialog', '/components/dialog', Record<never, never>, Record<never, never>>,
    'components-expansion-panel': RouteRecordInfo<'components-expansion-panel', '/components/expansion-panel', Record<never, never>, Record<never, never>>,
    'components-list': RouteRecordInfo<'components-list', '/components/list', Record<never, never>, Record<never, never>>,
    'components-menu': RouteRecordInfo<'components-menu', '/components/menu', Record<never, never>, Record<never, never>>,
    'components-pagination': RouteRecordInfo<'components-pagination', '/components/pagination', Record<never, never>, Record<never, never>>,
    'components-progress-circular': RouteRecordInfo<'components-progress-circular', '/components/progress-circular', Record<never, never>, Record<never, never>>,
    'components-progress-linear': RouteRecordInfo<'components-progress-linear', '/components/progress-linear', Record<never, never>, Record<never, never>>,
    'components-snackbar': RouteRecordInfo<'components-snackbar', '/components/snackbar', Record<never, never>, Record<never, never>>,
    'components-tabs': RouteRecordInfo<'components-tabs', '/components/tabs', Record<never, never>, Record<never, never>>,
    'components-timeline': RouteRecordInfo<'components-timeline', '/components/timeline', Record<never, never>, Record<never, never>>,
    'components-tooltip': RouteRecordInfo<'components-tooltip', '/components/tooltip', Record<never, never>, Record<never, never>>,
    'configurations': RouteRecordInfo<'configurations', '/configurations', Record<never, never>, Record<never, never>>,
    'configurations-baserates': RouteRecordInfo<'configurations-baserates', '/configurations/baserates', Record<never, never>, Record<never, never>>,
    'configurations-components-anchor-manual': RouteRecordInfo<'configurations-components-anchor-manual', '/configurations/components/anchor-manual', Record<never, never>, Record<never, never>>,
    'configurations-components-bank-manual': RouteRecordInfo<'configurations-components-bank-manual', '/configurations/components/bank-manual', Record<never, never>, Record<never, never>>,
    'configurations-components-dealer-manual': RouteRecordInfo<'configurations-components-dealer-manual', '/configurations/components/dealer-manual', Record<never, never>, Record<never, never>>,
    'configurations-components-vendor-manual': RouteRecordInfo<'configurations-components-vendor-manual', '/configurations/components/vendor-manual', Record<never, never>, Record<never, never>>,
    'configurations-currency-converter': RouteRecordInfo<'configurations-currency-converter', '/configurations/currency-converter', Record<never, never>, Record<never, never>>,
    'configurations-dialogs-add-edit-rates-dialog': RouteRecordInfo<'configurations-dialogs-add-edit-rates-dialog', '/configurations/dialogs/AddEditRatesDialog', Record<never, never>, Record<never, never>>,
    'configurations-dialogs-add-industry-dialog': RouteRecordInfo<'configurations-dialogs-add-industry-dialog', '/configurations/dialogs/AddIndustryDialog', Record<never, never>, Record<never, never>>,
    'configurations-dialogs-edit-bank-dialog': RouteRecordInfo<'configurations-dialogs-edit-bank-dialog', '/configurations/dialogs/EditBankDialog', Record<never, never>, Record<never, never>>,
    'configurations-dialogs-edit-bank-masterlist-dialog': RouteRecordInfo<'configurations-dialogs-edit-bank-masterlist-dialog', '/configurations/dialogs/EditBankMasterlistDialog', Record<never, never>, Record<never, never>>,
    'configurations-dialogs-edit-currencies-dialog': RouteRecordInfo<'configurations-dialogs-edit-currencies-dialog', '/configurations/dialogs/EditCurrenciesDialog', Record<never, never>, Record<never, never>>,
    'configurations-dialogs-edit-industry-dialog': RouteRecordInfo<'configurations-dialogs-edit-industry-dialog', '/configurations/dialogs/EditIndustryDialog', Record<never, never>, Record<never, never>>,
    'configurations-dialogs-edit-rates-dialog': RouteRecordInfo<'configurations-dialogs-edit-rates-dialog', '/configurations/dialogs/EditRatesDialog', Record<never, never>, Record<never, never>>,
    'configurations-dialogs-edit-taxes-dialog': RouteRecordInfo<'configurations-dialogs-edit-taxes-dialog', '/configurations/dialogs/EditTaxesDialog', Record<never, never>, Record<never, never>>,
    'configurations-email-templates': RouteRecordInfo<'configurations-email-templates', '/configurations/email-templates', Record<never, never>, Record<never, never>>,
    'configurations-faqs': RouteRecordInfo<'configurations-faqs', '/configurations/faqs', Record<never, never>, Record<never, never>>,
    'configurations-industries': RouteRecordInfo<'configurations-industries', '/configurations/industries', Record<never, never>, Record<never, never>>,
    'configurations-noa-templates': RouteRecordInfo<'configurations-noa-templates', '/configurations/noa-templates', Record<never, never>, Record<never, never>>,
    'configurations-old-terms-conditions': RouteRecordInfo<'configurations-old-terms-conditions', '/configurations/old-terms-conditions', Record<never, never>, Record<never, never>>,
    'configurations-system-configurations': RouteRecordInfo<'configurations-system-configurations', '/configurations/system-configurations', Record<never, never>, Record<never, never>>,
    'configurations-terms-conditions': RouteRecordInfo<'configurations-terms-conditions', '/configurations/terms-conditions', Record<never, never>, Record<never, never>>,
    'configurations-terms-conditions copy': RouteRecordInfo<'configurations-terms-conditions copy', '/configurations/terms-conditions copy', Record<never, never>, Record<never, never>>,
    'configurations-user-manuals': RouteRecordInfo<'configurations-user-manuals', '/configurations/user-manuals', Record<never, never>, Record<never, never>>,
    'configurations-view-add-email-template': RouteRecordInfo<'configurations-view-add-email-template', '/configurations/view/add-email-template', Record<never, never>, Record<never, never>>,
    'configurations-view-add-faq': RouteRecordInfo<'configurations-view-add-faq', '/configurations/view/add-faq', Record<never, never>, Record<never, never>>,
    'configurations-view-add-noa-template': RouteRecordInfo<'configurations-view-add-noa-template', '/configurations/view/add-noa-template', Record<never, never>, Record<never, never>>,
    'configurations-view-add-terms-conditions': RouteRecordInfo<'configurations-view-add-terms-conditions', '/configurations/view/add-terms-conditions', Record<never, never>, Record<never, never>>,
    'configurations-view-edit-email-template': RouteRecordInfo<'configurations-view-edit-email-template', '/configurations/view/edit-email-template', Record<never, never>, Record<never, never>>,
    'configurations-view-edit-noa-template': RouteRecordInfo<'configurations-view-edit-noa-template', '/configurations/view/edit-noa-template', Record<never, never>, Record<never, never>>,
    'configurations-view-edit-terms': RouteRecordInfo<'configurations-view-edit-terms', '/configurations/view/edit-terms', Record<never, never>, Record<never, never>>,
    'configurations-view-form-email-details': RouteRecordInfo<'configurations-view-form-email-details', '/configurations/view/form/email-details', Record<never, never>, Record<never, never>>,
    'configurations-view-form-header-footer': RouteRecordInfo<'configurations-view-form-header-footer', '/configurations/view/form/header-footer', Record<never, never>, Record<never, never>>,
    'configurations-view-system-config-config-file': RouteRecordInfo<'configurations-view-system-config-config-file', '/configurations/view/system-config/config-file', Record<never, never>, Record<never, never>>,
    'configurations-view-system-config-general-settings': RouteRecordInfo<'configurations-view-system-config-general-settings', '/configurations/view/system-config/general-settings', Record<never, never>, Record<never, never>>,
    'configurations-view-system-config-terms-conditions': RouteRecordInfo<'configurations-view-system-config-terms-conditions', '/configurations/view/system-config/terms-conditions', Record<never, never>, Record<never, never>>,
    'configurations-view-system-config-user-manuals': RouteRecordInfo<'configurations-view-system-config-user-manuals', '/configurations/view/system-config/user-manuals', Record<never, never>, Record<never, never>>,
    'crm-home': RouteRecordInfo<'crm-home', '/crm/home', Record<never, never>, Record<never, never>>,
    'crm-pipeline-closed-tab': RouteRecordInfo<'crm-pipeline-closed-tab', '/crm/pipeline/closed/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'crm-pipeline-contacts-tab': RouteRecordInfo<'crm-pipeline-contacts-tab', '/crm/pipeline/contacts/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'crm-pipeline-leads-tab': RouteRecordInfo<'crm-pipeline-leads-tab', '/crm/pipeline/leads/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'crm-pipeline-new': RouteRecordInfo<'crm-pipeline-new', '/crm/pipeline/new', Record<never, never>, Record<never, never>>,
    'crm-pipeline-opportunity-tab': RouteRecordInfo<'crm-pipeline-opportunity-tab', '/crm/pipeline/opportunity/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'dashboards-analytics': RouteRecordInfo<'dashboards-analytics', '/dashboards/analytics', Record<never, never>, Record<never, never>>,
    'dashboards-crm': RouteRecordInfo<'dashboards-crm', '/dashboards/crm', Record<never, never>, Record<never, never>>,
    'dashboards-ecommerce': RouteRecordInfo<'dashboards-ecommerce', '/dashboards/ecommerce', Record<never, never>, Record<never, never>>,
    'dealers': RouteRecordInfo<'dealers', '/dealers', Record<never, never>, Record<never, never>>,
    'documents-uuid': RouteRecordInfo<'documents-uuid', '/documents/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    'documents-uploaded': RouteRecordInfo<'documents-uploaded', '/documents/uploaded', Record<never, never>, Record<never, never>>,
    'expense-management': RouteRecordInfo<'expense-management', '/expense/management', Record<never, never>, Record<never, never>>,
    'extensions-swiper': RouteRecordInfo<'extensions-swiper', '/extensions/swiper', Record<never, never>, Record<never, never>>,
    'extensions-tour': RouteRecordInfo<'extensions-tour', '/extensions/tour', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'forms-autocomplete': RouteRecordInfo<'forms-autocomplete', '/forms/autocomplete', Record<never, never>, Record<never, never>>,
    'forms-checkbox': RouteRecordInfo<'forms-checkbox', '/forms/checkbox', Record<never, never>, Record<never, never>>,
    'forms-combobox': RouteRecordInfo<'forms-combobox', '/forms/combobox', Record<never, never>, Record<never, never>>,
    'forms-custom-input': RouteRecordInfo<'forms-custom-input', '/forms/custom-input', Record<never, never>, Record<never, never>>,
    'forms-date-time-picker': RouteRecordInfo<'forms-date-time-picker', '/forms/date-time-picker', Record<never, never>, Record<never, never>>,
    'forms-editors': RouteRecordInfo<'forms-editors', '/forms/editors', Record<never, never>, Record<never, never>>,
    'forms-file-input': RouteRecordInfo<'forms-file-input', '/forms/file-input', Record<never, never>, Record<never, never>>,
    'forms-form-layouts': RouteRecordInfo<'forms-form-layouts', '/forms/form-layouts', Record<never, never>, Record<never, never>>,
    'forms-form-validation': RouteRecordInfo<'forms-form-validation', '/forms/form-validation', Record<never, never>, Record<never, never>>,
    'forms-form-wizard-icons': RouteRecordInfo<'forms-form-wizard-icons', '/forms/form-wizard-icons', Record<never, never>, Record<never, never>>,
    'forms-form-wizard-numbered': RouteRecordInfo<'forms-form-wizard-numbered', '/forms/form-wizard-numbered', Record<never, never>, Record<never, never>>,
    'forms-radio': RouteRecordInfo<'forms-radio', '/forms/radio', Record<never, never>, Record<never, never>>,
    'forms-range-slider': RouteRecordInfo<'forms-range-slider', '/forms/range-slider', Record<never, never>, Record<never, never>>,
    'forms-rating': RouteRecordInfo<'forms-rating', '/forms/rating', Record<never, never>, Record<never, never>>,
    'forms-select': RouteRecordInfo<'forms-select', '/forms/select', Record<never, never>, Record<never, never>>,
    'forms-slider': RouteRecordInfo<'forms-slider', '/forms/slider', Record<never, never>, Record<never, never>>,
    'forms-switch': RouteRecordInfo<'forms-switch', '/forms/switch', Record<never, never>, Record<never, never>>,
    'forms-textarea': RouteRecordInfo<'forms-textarea', '/forms/textarea', Record<never, never>, Record<never, never>>,
    'forms-textfield': RouteRecordInfo<'forms-textfield', '/forms/textfield', Record<never, never>, Record<never, never>>,
    'front-pages-checkout': RouteRecordInfo<'front-pages-checkout', '/front-pages/checkout', Record<never, never>, Record<never, never>>,
    'front-pages-help-center': RouteRecordInfo<'front-pages-help-center', '/front-pages/help-center', Record<never, never>, Record<never, never>>,
    'front-pages-help-center-article-title': RouteRecordInfo<'front-pages-help-center-article-title', '/front-pages/help-center/article/:title', { title: ParamValue<true> }, { title: ParamValue<false> }>,
    'front-pages-landing-page': RouteRecordInfo<'front-pages-landing-page', '/front-pages/landing-page', Record<never, never>, Record<never, never>>,
    'front-pages-payment': RouteRecordInfo<'front-pages-payment', '/front-pages/payment', Record<never, never>, Record<never, never>>,
    'front-pages-pricing': RouteRecordInfo<'front-pages-pricing', '/front-pages/pricing', Record<never, never>, Record<never, never>>,
    'help': RouteRecordInfo<'help', '/help', Record<never, never>, Record<never, never>>,
    'home': RouteRecordInfo<'home', '/home', Record<never, never>, Record<never, never>>,
    'invoices': RouteRecordInfo<'invoices', '/invoices', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'login1': RouteRecordInfo<'login1', '/login1', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'notifications': RouteRecordInfo<'notifications', '/notifications', Record<never, never>, Record<never, never>>,
    'pages-account-settings-tab': RouteRecordInfo<'pages-account-settings-tab', '/pages/account-settings/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'pages-authentication-forgot-password-v1': RouteRecordInfo<'pages-authentication-forgot-password-v1', '/pages/authentication/forgot-password-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-forgot-password-v2': RouteRecordInfo<'pages-authentication-forgot-password-v2', '/pages/authentication/forgot-password-v2', Record<never, never>, Record<never, never>>,
    'pages-authentication-login-v1': RouteRecordInfo<'pages-authentication-login-v1', '/pages/authentication/login-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-login-v2': RouteRecordInfo<'pages-authentication-login-v2', '/pages/authentication/login-v2', Record<never, never>, Record<never, never>>,
    'pages-authentication-register-multi-steps': RouteRecordInfo<'pages-authentication-register-multi-steps', '/pages/authentication/register-multi-steps', Record<never, never>, Record<never, never>>,
    'pages-authentication-register-v1': RouteRecordInfo<'pages-authentication-register-v1', '/pages/authentication/register-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-register-v2': RouteRecordInfo<'pages-authentication-register-v2', '/pages/authentication/register-v2', Record<never, never>, Record<never, never>>,
    'pages-authentication-reset-password-v1': RouteRecordInfo<'pages-authentication-reset-password-v1', '/pages/authentication/reset-password-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-reset-password-v2': RouteRecordInfo<'pages-authentication-reset-password-v2', '/pages/authentication/reset-password-v2', Record<never, never>, Record<never, never>>,
    'pages-authentication-two-steps-v1': RouteRecordInfo<'pages-authentication-two-steps-v1', '/pages/authentication/two-steps-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-two-steps-v2': RouteRecordInfo<'pages-authentication-two-steps-v2', '/pages/authentication/two-steps-v2', Record<never, never>, Record<never, never>>,
    'pages-authentication-verify-email-v1': RouteRecordInfo<'pages-authentication-verify-email-v1', '/pages/authentication/verify-email-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-verify-email-v2': RouteRecordInfo<'pages-authentication-verify-email-v2', '/pages/authentication/verify-email-v2', Record<never, never>, Record<never, never>>,
    'pages-cards-card-actions': RouteRecordInfo<'pages-cards-card-actions', '/pages/cards/card-actions', Record<never, never>, Record<never, never>>,
    'pages-cards-card-advance': RouteRecordInfo<'pages-cards-card-advance', '/pages/cards/card-advance', Record<never, never>, Record<never, never>>,
    'pages-cards-card-basic': RouteRecordInfo<'pages-cards-card-basic', '/pages/cards/card-basic', Record<never, never>, Record<never, never>>,
    'pages-cards-card-statistics': RouteRecordInfo<'pages-cards-card-statistics', '/pages/cards/card-statistics', Record<never, never>, Record<never, never>>,
    'pages-cards-card-widgets': RouteRecordInfo<'pages-cards-card-widgets', '/pages/cards/card-widgets', Record<never, never>, Record<never, never>>,
    'pages-dialog-examples': RouteRecordInfo<'pages-dialog-examples', '/pages/dialog-examples', Record<never, never>, Record<never, never>>,
    'pages-faq': RouteRecordInfo<'pages-faq', '/pages/faq', Record<never, never>, Record<never, never>>,
    'pages-icons': RouteRecordInfo<'pages-icons', '/pages/icons', Record<never, never>, Record<never, never>>,
    'pages-misc-coming-soon': RouteRecordInfo<'pages-misc-coming-soon', '/pages/misc/coming-soon', Record<never, never>, Record<never, never>>,
    'pages-misc-under-maintenance': RouteRecordInfo<'pages-misc-under-maintenance', '/pages/misc/under-maintenance', Record<never, never>, Record<never, never>>,
    'pages-pricing': RouteRecordInfo<'pages-pricing', '/pages/pricing', Record<never, never>, Record<never, never>>,
    'pages-typography': RouteRecordInfo<'pages-typography', '/pages/typography', Record<never, never>, Record<never, never>>,
    'pages-user-profile-tab': RouteRecordInfo<'pages-user-profile-tab', '/pages/user-profile/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'pipeline-closed-tab': RouteRecordInfo<'pipeline-closed-tab', '/pipeline/closed/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'pipeline-contacts-tab': RouteRecordInfo<'pipeline-contacts-tab', '/pipeline/contacts/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'pipeline-edit-id': RouteRecordInfo<'pipeline-edit-id', '/pipeline/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pipeline-leads-tab': RouteRecordInfo<'pipeline-leads-tab', '/pipeline/leads/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'pipeline-leads-new-id': RouteRecordInfo<'pipeline-leads-new-id', '/pipeline/leads/new/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pipeline-new': RouteRecordInfo<'pipeline-new', '/pipeline/new', Record<never, never>, Record<never, never>>,
    'pipeline-opportunity-tab': RouteRecordInfo<'pipeline-opportunity-tab', '/pipeline/opportunity/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'pipeline-opportunity-new-id': RouteRecordInfo<'pipeline-opportunity-new-id', '/pipeline/opportunity/new/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'pipeline-view-id': RouteRecordInfo<'pipeline-view-id', '/pipeline/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'program-vendor': RouteRecordInfo<'program-vendor', '/program/vendor', Record<never, never>, Record<never, never>>,
    'program-view-id': RouteRecordInfo<'program-view-id', '/program/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'program-view-add-program': RouteRecordInfo<'program-view-add-program', '/program/view/add-program', Record<never, never>, Record<never, never>>,
    'program-view-edit-program-id': RouteRecordInfo<'program-view-edit-program-id', '/program/view/edit-program/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'program-view-form-bank-details': RouteRecordInfo<'program-view-form-bank-details', '/program/view/form/bank-details', Record<never, never>, Record<never, never>>,
    'program-view-form-discount-fees': RouteRecordInfo<'program-view-form-discount-fees', '/program/view/form/discount-fees', Record<never, never>, Record<never, never>>,
    'program-view-form-email-mobile-details': RouteRecordInfo<'program-view-form-email-mobile-details', '/program/view/form/email-mobile-details', Record<never, never>, Record<never, never>>,
    'program-view-form-program-details': RouteRecordInfo<'program-view-form-program-details', '/program/view/form/program-details', Record<never, never>, Record<never, never>>,
    'program-view-program-panel': RouteRecordInfo<'program-view-program-panel', '/program/view/ProgramPanel', Record<never, never>, Record<never, never>>,
    'programs': RouteRecordInfo<'programs', '/programs', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'report-activity': RouteRecordInfo<'report-activity', '/report/activity', Record<never, never>, Record<never, never>>,
    'report-anchors': RouteRecordInfo<'report-anchors', '/report/anchors', Record<never, never>, Record<never, never>>,
    'report-vendors': RouteRecordInfo<'report-vendors', '/report/vendors', Record<never, never>, Record<never, never>>,
    'reports': RouteRecordInfo<'reports', '/reports', Record<never, never>, Record<never, never>>,
    'reports-allinvoice': RouteRecordInfo<'reports-allinvoice', '/reports/allinvoice', Record<never, never>, Record<never, never>>,
    'reports-dfpotential-financing': RouteRecordInfo<'reports-dfpotential-financing', '/reports/dfpotential/financing', Record<never, never>, Record<never, never>>,
    'reports-expiredinvoice': RouteRecordInfo<'reports-expiredinvoice', '/reports/expiredinvoice', Record<never, never>, Record<never, never>>,
    'reports-invoice': RouteRecordInfo<'reports-invoice', '/reports/invoice', Record<never, never>, Record<never, never>>,
    'reports-potential-financing': RouteRecordInfo<'reports-potential-financing', '/reports/potential/financing', Record<never, never>, Record<never, never>>,
    'reports-requestedinvoice': RouteRecordInfo<'reports-requestedinvoice', '/reports/requestedinvoice', Record<never, never>, Record<never, never>>,
    'reports-vfpotential-financing': RouteRecordInfo<'reports-vfpotential-financing', '/reports/vfpotential/financing', Record<never, never>, Record<never, never>>,
    'reset-password-token': RouteRecordInfo<'reset-password-token', '/reset-password/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    'settings-tab': RouteRecordInfo<'settings-tab', '/settings/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'source-analysis': RouteRecordInfo<'source-analysis', '/source/analysis', Record<never, never>, Record<never, never>>,
    'tables-data-table': RouteRecordInfo<'tables-data-table', '/tables/data-table', Record<never, never>, Record<never, never>>,
    'tables-simple-table': RouteRecordInfo<'tables-simple-table', '/tables/simple-table', Record<never, never>, Record<never, never>>,
    'two-steps': RouteRecordInfo<'two-steps', '/two-steps', Record<never, never>, Record<never, never>>,
    'users-add-new-user': RouteRecordInfo<'users-add-new-user', '/users/AddNewUser', Record<never, never>, Record<never, never>>,
    'users-all-roles': RouteRecordInfo<'users-all-roles', '/users/AllRoles', Record<never, never>, Record<never, never>>,
    'users-edit-role-id': RouteRecordInfo<'users-edit-role-id', '/users/edit-role/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'users-edit-role-all-roles': RouteRecordInfo<'users-edit-role-all-roles', '/users/edit-role/AllRoles', Record<never, never>, Record<never, never>>,
    'users-list': RouteRecordInfo<'users-list', '/users/list', Record<never, never>, Record<never, never>>,
    'users-permission': RouteRecordInfo<'users-permission', '/users/permission', Record<never, never>, Record<never, never>>,
    'users-role': RouteRecordInfo<'users-role', '/users/role', Record<never, never>, Record<never, never>>,
    'users-view-id': RouteRecordInfo<'users-view-id', '/users/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'users-view-user-bio-panel': RouteRecordInfo<'users-view-user-bio-panel', '/users/view/UserBioPanel', Record<never, never>, Record<never, never>>,
    'users-view-user-roles': RouteRecordInfo<'users-view-user-roles', '/users/view/UserRoles', Record<never, never>, Record<never, never>>,
    'vendor': RouteRecordInfo<'vendor', '/vendor', Record<never, never>, Record<never, never>>,
    'vendors': RouteRecordInfo<'vendors', '/vendors', Record<never, never>, Record<never, never>>,
    'wizard-examples-checkout': RouteRecordInfo<'wizard-examples-checkout', '/wizard-examples/checkout', Record<never, never>, Record<never, never>>,
    'wizard-examples-create-deal': RouteRecordInfo<'wizard-examples-create-deal', '/wizard-examples/create-deal', Record<never, never>, Record<never, never>>,
    'wizard-examples-property-listing': RouteRecordInfo<'wizard-examples-property-listing', '/wizard-examples/property-listing', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
